dist: trusty
sudo: required
before_install:
  - sudo apt-get update -q
  - sudo apt update && sudo apt install ffmpeg libav-tools x264 x265 -y
language: node_js
sudo: required
node_js:
- lts/*
script:
- npm run test
